### ISSUE TITLE
WPML compatibility Issues

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/woo-refund-and-exchange-lite#36]
MakeWebBetter on the sidebar is being translated that's why CSS disturbed:
![image](https://user-images.githubusercontent.com/85384857/144703572-2962b31b-2d94-4b3c-ada3-fd6a3a9e4e0f.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
