### ISSUE TITLE
Issue with WP-Bakery compatibility

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/woo-refund-and-exchange-lite#37]
WordPress version: 5.8.2
WooCommerce version: 5.9.0
Version: 4.0.0
Description:
RMA element can't be found in Wp-Bakery 
![image](https://user-images.githubusercontent.com/85384857/144841340-7798dabf-f84b-403d-94c3-6f739cd24dbd.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
