### ISSUE TITLE
Issue with API setting

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/woo-refund-and-exchange-lite#38]
WordPress version: 5.8.2
WooCommerce version: 5.9.0
Version: 4.0.0
Description:
### Responce for some data
**1. Wrong Order Id in accept request:**
![image](https://user-images.githubusercontent.com/85384857/144868586-84f527d3-55c6-4474-885e-ae92ac442405.png)
**2. When an order is cancelled:**
![image](https://user-images.githubusercontent.com/85384857/144869347-d087cbe4-1127-46aa-b16c-f8c65e4aaa13.png)
**3. When an order is approved:**
![image](https://user-images.githubusercontent.com/85384857/144869898-f91f006a-4eef-4bec-863e-f3ab3b2c2f30.png)
**4. When order id is wrong but refund reason is also not provided:**
![image](https://user-images.githubusercontent.com/85384857/144870550-d2052d01-c316-4798-bfdd-04f543206036.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
The text is not getting correct:
![image](https://user-images.githubusercontent.com/85384857/145667079-98af8f13-516c-4073-8182-3fcc68b17509.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
