### ISSUE TITLE
QA/PHPcs Issues

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/woo-refund-and-exchange-lite#39]
DOC:
https://docs.google.com/document/d/1mSnRstSd3bU0C7r46x5YAGub5vf4kRh6Yw-zFt0yE00/edit?usp=sharing

Files:
[ORG.zip](https://github.com/Makewebbetter/woo-refund-and-exchange-lite/files/7932706/ORG.zip)
[woo-refund-and-exchange-lite.zip](https://github.com/Makewebbetter/woo-refund-and-exchange-lite/files/7932707/woo-refund-and-exchange-lite.zip)
[PRO.zip](https://github.com/Makewebbetter/woo-refund-and-exchange-lite/files/7932711/PRO.zip)
[woocommerce-rma-for-return-refund-and-exchange.zip](https://github.com/Makewebbetter/woo-refund-and-exchange-lite/files/7932712/woocommerce-rma-for-return-refund-and-exchange.zip)

Language :
Some strings are not translated
![image](https://user-images.githubusercontent.com/85384857/150959592-a7058c8a-ba5b-4fdd-bf59-5aba600c8a36.png)

**Comment by mohammaddanish-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
